// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/ctrl/ctrl.go
//
// Generated by this command:
//
//	mockgen -source=./internal/ctrl/ctrl.go -destination=mocks/mock_repos.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JMURv/effectiveMobile/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSongsRepo is a mock of SongsRepo interface.
type MockSongsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSongsRepoMockRecorder
}

// MockSongsRepoMockRecorder is the mock recorder for MockSongsRepo.
type MockSongsRepoMockRecorder struct {
	mock *MockSongsRepo
}

// NewMockSongsRepo creates a new mock instance.
func NewMockSongsRepo(ctrl *gomock.Controller) *MockSongsRepo {
	mock := &MockSongsRepo{ctrl: ctrl}
	mock.recorder = &MockSongsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSongsRepo) EXPECT() *MockSongsRepoMockRecorder {
	return m.recorder
}

// CreateSong mocks base method.
func (m *MockSongsRepo) CreateSong(ctx context.Context, req *model.Song) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSong", ctx, req)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSong indicates an expected call of CreateSong.
func (mr *MockSongsRepoMockRecorder) CreateSong(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSong", reflect.TypeOf((*MockSongsRepo)(nil).CreateSong), ctx, req)
}

// DeleteSong mocks base method.
func (m *MockSongsRepo) DeleteSong(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSong", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSong indicates an expected call of DeleteSong.
func (mr *MockSongsRepoMockRecorder) DeleteSong(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSong", reflect.TypeOf((*MockSongsRepo)(nil).DeleteSong), ctx, id)
}

// GetSong mocks base method.
func (m *MockSongsRepo) GetSong(ctx context.Context, id uint64, page, size int) (*model.PaginatedSongs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSong", ctx, id, page, size)
	ret0, _ := ret[0].(*model.PaginatedSongs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSong indicates an expected call of GetSong.
func (mr *MockSongsRepoMockRecorder) GetSong(ctx, id, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSong", reflect.TypeOf((*MockSongsRepo)(nil).GetSong), ctx, id, page, size)
}

// ListSongs mocks base method.
func (m *MockSongsRepo) ListSongs(ctx context.Context, page, size int, filters map[string]any) (*model.PaginatedSongs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSongs", ctx, page, size, filters)
	ret0, _ := ret[0].(*model.PaginatedSongs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSongs indicates an expected call of ListSongs.
func (mr *MockSongsRepoMockRecorder) ListSongs(ctx, page, size, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSongs", reflect.TypeOf((*MockSongsRepo)(nil).ListSongs), ctx, page, size, filters)
}

// UpdateSong mocks base method.
func (m *MockSongsRepo) UpdateSong(ctx context.Context, req *model.Song) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSong", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSong indicates an expected call of UpdateSong.
func (mr *MockSongsRepoMockRecorder) UpdateSong(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSong", reflect.TypeOf((*MockSongsRepo)(nil).UpdateSong), ctx, req)
}

// MockAPIRepo is a mock of APIRepo interface.
type MockAPIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAPIRepoMockRecorder
}

// MockAPIRepoMockRecorder is the mock recorder for MockAPIRepo.
type MockAPIRepoMockRecorder struct {
	mock *MockAPIRepo
}

// NewMockAPIRepo creates a new mock instance.
func NewMockAPIRepo(ctrl *gomock.Controller) *MockAPIRepo {
	mock := &MockAPIRepo{ctrl: ctrl}
	mock.recorder = &MockAPIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIRepo) EXPECT() *MockAPIRepoMockRecorder {
	return m.recorder
}

// FetchSongDetail mocks base method.
func (m *MockAPIRepo) FetchSongDetail(group, song string) (*model.SongDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSongDetail", group, song)
	ret0, _ := ret[0].(*model.SongDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSongDetail indicates an expected call of FetchSongDetail.
func (mr *MockAPIRepoMockRecorder) FetchSongDetail(group, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSongDetail", reflect.TypeOf((*MockAPIRepo)(nil).FetchSongDetail), group, song)
}
